roles:
  - name: admin
    label: 系统管理员
    source: system
  - name: standard
    label: 标准用户
    source: system

objects:
  - name: user
    label: 用户
    description: 系统用户
    source: system
    name_field: name
    fields:
      - name: name
        label: 姓名
        data_type: Text
        source: system
      - name: email
        label: 邮箱
        data_type: Text
        is_required: true
        source: system
      - name: password
        label: 密码哈希
        data_type: Text
        source: system
      - name: role
        label: 角色
        data_type: Metadata
        metadata_type: role
        source: system

  - name: account
    label: 客户
    description: 企业客户信息
    source: system
    name_field: name
    fields:
      - name: name
        label: 客户名称
        data_type: Text
        is_required: true
        source: system
      - name: industry
        label: 行业
        data_type: Picklist
        source: system
        options:
          - name: technology
            label: 科技
          - name: finance
            label: 金融
          - name: healthcare
            label: 医疗健康
          - name: retail
            label: 零售
          - name: manufacturing
            label: 制造
          - name: energy
            label: 能源
          - name: consulting
            label: 咨询
          - name: other
            label: 其他
      - name: type
        label: 类型
        data_type: Picklist
        source: system
        options:
          - name: prospect
            label: 潜在客户
          - name: customer
            label: 现有客户
          - name: partner
            label: 合作伙伴
          - name: vendor
            label: 供应商
      - name: website
        label: 网站
        data_type: Text
        source: system
      - name: phone
        label: 电话
        data_type: Text
        source: system
      - name: employees
        label: 员工数
        data_type: Number
        source: system
      - name: annual_revenue
        label: 年收入
        data_type: Number
        source: system

  - name: product
    label: 产品
    description: 公司产品（药品）
    source: system
    name_field: name
    fields:
      - name: name
        label: 产品名称
        data_type: Text
        is_required: true
        source: system
      - name: product_code
        label: 产品代码
        data_type: Text
        source: system
      - name: category
        label: 类别
        data_type: Picklist
        source: system
        options:
          - name: prescription
            label: 处方药
          - name: otc
            label: 非处方药 (OTC)
          - name: supplement
            label: 保健品
          - name: device
            label: 医疗器械
      - name: price
        label: 单价
        data_type: Number
        source: system
      - name: description
        label: 描述
        data_type: Text
        source: system

  - name: call
    label: 拜访记录
    description: 销售拜访与跟进记录
    source: system
    name_field: subject
    fields:
      - name: subject
        label: 主题
        data_type: Text
        is_required: true
        source: system
      - name: account_id
        label: 关联客户
        data_type: Lookup
        lookup_object: account
        is_required: true
        source: system
      - name: product_id
        label: 关联产品
        data_type: Lookup
        lookup_object: product
        source: system
      - name: call_type
        label: 拜访类型
        data_type: Picklist
        source: system
        options:
          - name: call
            label: 电话
          - name: meeting
            label: 线下会议
          - name: email
            label: 邮件
          - name: other
            label: 其他
      - name: status
        label: 状态
        data_type: Picklist
        source: system
        options:
          - name: planned
            label: 计划中
          - name: completed
            label: 已完成
          - name: cancelled
            label: 已取消
      - name: call_date
        label: 拜访时间
        data_type: Datetime
        is_required: true
        source: system
      - name: duration
        label: 时长 (分钟)
        data_type: Number
        source: system
      - name: description
        label: 详细描述
        data_type: Text
        source: system

  - name: cs_expense
    label: 费用记录
    description: 销售过程中的费用报销记录
    source: custom
    name_field: cs_title
    fields:
      - name: cs_title
        label: 费用摘要
        data_type: Text
        is_required: true
        source: custom
      - name: cs_amount
        label: 金额
        data_type: Number
        is_required: true
        source: custom
      - name: cs_date
        label: 发生日期
        data_type: Date
        is_required: true
        source: custom
      - name: cs_category
        label: 费用类别
        data_type: Picklist
        source: custom
        options:
          - name: transport
            label: 交通费
          - name: dining
            label: 餐饮费
          - name: accommodation
            label: 住宿费
          - name: other
            label: 其他
      - name: cs_call_id
        label: 关联拜访
        data_type: Lookup
        lookup_object: call
        source: custom
